### ISSUE TITLE
Add npm dependencies

### ISSUE THREAD

**Issue by jantimon** [chicagogrooves/meteor-package-kitchen#7]
Hi,

The package kitchen looks awesome! :+1: 
Would suggest one additional feature: Generating the npm dependency block

```
Npm.depends({
  "a-funky-module": "1.2.3"
});
```

It is kind of anoying to search for the version so it would be cool if the package-kitchen would resolve the version for us and generates the Npm.depends block: https://docs.npmjs.com/api/search

**Comment by chicagogrooves** [comment]
Looks like I just got it figured out ! Want to see if that works ?

**Comment by jantimon** [comment]
http://package-kitchen.meteor.com/ seems to be down

**Comment by chicagogrooves** [comment]
Yeah, package exports are broken. Asking for help here: http://stackoverflow.com/questions/30553376/meteor-package-export-sometimes-missing

**Comment by chicagogrooves** [comment]
@jantimon - it's deployed at last !
